[package]
name = "numerical-methods"
version = "0.1.0"
authors = ["Ken Butler <Ken.Butler.AE@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]